### PR TITLE
Save and add entry

### PR DESCRIPTION
**Pull request by zontarian**

### CODE REVIEW

**Comment by aheinze** [comment]
hi,

thanks for the contribution.... these are many changes in one commit. I need to go through the changes in detail.

**Comment by florianletsch** [comment]
Maybe you can tidy up the PR a bit, so that Artur has to review less? 

Suggestion: Remove all `console.log()` lines and make sure you haven't accidentally added extra spaces or lines of whitespace (seems to have happened in a few files).

**Comment by zontarian** [comment]
Hello.

To be honest, I did a mess.

I didn't really want to submit a PR (I wanted to submit a PR on my fork, 
not on the main fork) moreover I wrote to aRthur and he didn't seem very 
interested in my contributions.
I will surely tidy up a bit, but I have a problem that I must overcome 
with GIT..

I really wanted to dubmit different commits and PR with single 
modifications, and not one bulk.. but I don't seem able to do it. As 
soon as I add a feature, it gets added to the PR. I know I should add a 
feature, do a commit and PR, then do a revert to main, create another 
branch, do another modification, and repeat the commit/PR cycle.. but it 
is difficult for me.

Thanks for your time. I will do my best to correct what I can. I really 
like Cockpit

Thanks


Walter


On 11/07/16 10:09, Florian Letsch wrote:
>
> Maybe you can tidy up the PR a bit, so that Artur has to review less?
>
> Suggestion: Remove all |console.log()| lines and make sure you haven't 
> accidentally added extra spaces or lines of whitespace (seems to have 
> happened in a few files).
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/COCOPi/cockpit/pull/422#issuecomment-231668055>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/ACvUcbGNsNw7n5s0Olg1CVHqw3K1M2ANks5qUfoegaJpZM4JIpH5>.
>

-- 
Walter Gamba
Amministratore Delegato
IAKTA srl

walter@iakta.it
+39 348 5610576
+39 011 3157422
+skype sakkio

IAKTA SRL - Ingegneria del software
www.iakta.it
via Agostino da Montefeltro, 2
10134 Torino
PIVA CF 08616480011

**Comment by zontarian** [comment]
Hi Artur,

please discard this PR. I don't know how to do it. In reality I wanted 
do do a PR on my fork, not on the main cockpit repo. There is still code 
that does not work in the Save & Add feature. It is not harmful but it's 
misleading so I don't think it is worth the effort to look trhough my 
submit in any case.

Thanks and sorry for the mess.

Walter


On 11/07/16 09:43, Artur wrote:
>
> hi,
>
> thanks for the contribution.... these are many changes in one commit. 
> I need to go through the changes in detail.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/COCOPi/cockpit/pull/422#issuecomment-231663332>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/ACvUcSmBggvcTqM11Jfu2r0Mv223dM1Dks5qUfQ2gaJpZM4JIpH5>.
>

-- 
Walter Gamba
Amministratore Delegato
IAKTA srl

walter@iakta.it
+39 348 5610576
+39 011 3157422
+skype sakkio

IAKTA SRL - Ingegneria del software
www.iakta.it
via Agostino da Montefeltro, 2
10134 Torino
PIVA CF 08616480011

**Comment by aheinze** [comment]
@zontarian No problem, glad you like Cockpit and thank you for your efforts!

**Pull request closed without merging**
